twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['_form.html.twig']
    #Added for Symfony 4.4
    exception_controller: null
