vich_uploader:
    db_driver: orm

    mappings:
        original_file:
            uri_prefix: /uploads/original
            upload_destination: '%kernel.project_dir%/public/uploads/original'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options:
                    length: 32

        final_file:
            uri_prefix: /uploads/final
            upload_destination: '%kernel.project_dir%/public/uploads/final'
