language: php

services:
  - postgresql

addons:
  postgresql: "9.6"

# Allows using containers
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

# Base versions to test raw with the Symfony latest version.
php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4snapshot"

matrix:
  fast_finish: true
  allow_failures:
    - php: "7.4snapshot"

before_install:
  - mkdir -p build/logs

install:
  # Libsodium pecl installation
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then pecl install libsodium ; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then echo "extension=libsodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi
  # Database creation
  - psql -c 'create database symfony;' -U postgres
  # Install application
  - composer install --verbose
  - composer update
  # Database configuration
  - cp .env.travis .env.local
  # Database migration
  - php bin/console doctrine:migrations:migrate -n
  # Data test installation
  - php bin/console doctrine:fixtures:load -n
  # Install assets
  # - yarn install
  # - yarn encore dev
  # Warm-up cache to avoid maximum execution time errors.
  - php bin/console cache:warmup
  # directories for coveralls
  - mkdir tests/_output/coveralls -p


# Run script and log coverage in the "build" directory
script:
  # Composer must be validated.
  - composer validate --no-interaction --ansi --verbose
  # Launch server
  - php bin/console server:start --no-interaction
  # Coverall tests
  - composer coverall-test
  # PHP MASS DETECTOR valid?
  - composer phpmd
  - composer phpmd-test
  # PHP CODE SNIFFER valid?
  - composer phpcs
  - composer phpcs-test
  # PHP CS FIXER valid?
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ]; then composer phpcsfixer ; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ]; then composer phpcsfixer-test ; fi

after_success:
  - cp tests/_output/coverage.xml build/logs/clover.xml
  - php vendor/bin/php-coveralls -v

# After a build, sends a notification to this e-mail with the build results.
notifications:
  email:
    recipients:
      - alexandre.tranchant@gmail.com
    on_success: never
    on_failure: change
