language: php

addons:
  mariadb: '10.2'

# Allows using containers
sudo: true

# Cache composer packages so "composer install" is faster
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

# Base versions to test raw with the Symfony latest version.
php:
  - "7.4"

node:
  - 10

matrix:
  fast_finish: true

before_install:
  - mkdir -p build/logs
  - export COMPOSER_PROCESS_TIMEOUT=3000
  - nvm install 10
install:
  # Database creation
  - mysql -e 'CREATE DATABASE symfony;'
  # Install application
  - composer install --verbose --no-interaction
  # Database configuration
  - cp .env.travis .env.local
  # Database migration
  - php bin/console doctrine:migrations:migrate -n
  # Data test installation
  - php bin/console doctrine:fixtures:load -n
  # Integration
  - php bin/console doctrine:query:sql "UPDATE ext_log_entries SET username = 'Intégrateur' WHERE username IS NULL"
  # Install assets
  - npm install
  - yarn install
  - yarn encore dev
  # Warm-up cache to avoid maximum execution time errors.
  - php bin/console cache:warmup
  # directories for coveralls
  - mkdir tests/_output/coveralls -p
  # to prepare test
  - cp tests/_data/upload.txt public/uploads/original/upload.txt
  - cp tests/_data/upload.txt public/uploads/final/upload.txt
  - php bin/console doctrine:query:sql "UPDATE te_order SET uuid = CONCAT('myManualValue-',id)"
  # Install symfony to have a web server
  - wget https://get.symfony.com/cli/installer -O - | bash
  - sudo mv /home/travis/.symfony/bin/symfony /usr/local/bin/symfony

# Run script and log coverage in the "build" directory
script:
  # Composer must be validated.
  - composer validate --no-interaction --ansi --verbose
  # Launch server
  - symfony serve -d --no-tls
  # Coverall tests
  - composer coverall-test

after_failure:
  - cat tests/_output/*.fail.html

after_success:
  - cp tests/_output/coverage.xml build/logs/clover.xml
  - php vendor/bin/php-coveralls -v
  # PHP MASS DETECTOR valid?
  - composer phpmd
  - composer phpmd-test
  # PHP CODE SNIFFER valid?
  - composer phpcs
  - composer phpcs-test
  # PHP CS FIXER valid?
  - composer phpcsfixer
  - composer phpcsfixer-test

# After a build, sends a notification to this e-mail with the build results.
notifications:
  email:
    recipients:
      - alexandre.tranchant@gmail.com
    on_success: change
    on_failure: change
