language: php

addons:
  mariadb: '10.2'

# Allows using containers
sudo: true

# Cache composer packages so "composer install" is faster
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

# Base versions to test raw with the Symfony latest version.
php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

matrix:
  fast_finish: true
  allow_failures:
    - php: "7.1"

before_install:
  - mkdir -p build/logs
  - export COMPOSER_PROCESS_TIMEOUT=3000
  # Copy composer.7-x.lock to composer.lock
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then cp composer.7-1.lock composer.lock ; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then cp composer.7-2.lock composer.lock ; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then cp composer.7-3.lock composer.lock ; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then cp composer.7-4.lock composer.lock ; fi
install:
  # Database creation
  - mysql -e 'CREATE DATABASE symfony;'
  # Install application
  - composer install --verbose --no-interaction
  # Database configuration
  - cp .env.travis .env.local
  # Database migration
  - php bin/console doctrine:migrations:migrate -n
  # Data test installation
  - php bin/console doctrine:fixtures:load -n
  # Integration
  - php bin/console doctrine:query:sql "UPDATE ext_log_entries SET username = 'Intégrateur' WHERE username IS NULL"
  # Install assets
  - yarn install
  - yarn encore dev
  # Warm-up cache to avoid maximum execution time errors.
  - php bin/console cache:warmup
  # directories for coveralls
  - mkdir tests/_output/coveralls -p
  # to prepare test
  - cp tests/_data/upload.txt public/uploads/original/upload.txt
  - cp tests/_data/upload.txt public/uploads/final/upload.txt
  - php bin/console doctrine:query:sql "UPDATE te_order SET uuid = CONCAT('myManualValue-',id)"
  - wget https://get.symfony.com/cli/installer -O - | bash
  - mv /home/travis/.symfony/bin/symfony /usr/local/bin/symfony

# Run script and log coverage in the "build" directory
script:
  # Composer must be validated.
  # - composer validate --no-interaction --ansi --verbose
  # Launch server
  - symfony serve -d
  # Coverall tests
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then composer all-test ; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.4" ]; then composer coverall-test ; fi
  # PHP MASS DETECTOR valid?
  - composer phpmd
  - composer phpmd-test
  # PHP CODE SNIFFER valid?
  - composer phpcs
  - composer phpcs-test
  # PHP CS FIXER valid?
  - composer phpcsfixer
  - composer phpcsfixer-test

after_failure:
  - cat tests/_output/*.fail.html

after_success:
  - cp tests/_output/coverage.xml build/logs/clover.xml
  - php vendor/bin/php-coveralls -v

# After a build, sends a notification to this e-mail with the build results.
notifications:
  email:
    recipients:
      - alexandre.tranchant@gmail.com
    on_success: never
    on_failure: change
